### ISSUE TITLE
Generic in a generic issue

### ISSUE THREAD

**Issue by lobodart** [nicolasdao/graphql-s2s#7]
Hi,
I'm trying to implement connections to use Relay as GraphQL client but I'm stuck with generics.
What I am trying to do:

```
type Edge<T> {
  node: T
  cursor: ID
}

type PageInfo {
  start_cursor: String
  end_cursor: String
  has_next_page: Boolean
  has_previous_page: Boolean
}

type Page<U> {
  total_count: Int
  edges: [Edge<U>]  // <------- Problem is here
  page_info: PageInfo
}

type Query {
  users: Page<User>
}
```

Here is the error I have:

```
Error: Schema error: Cannot find any definition for generic type starting with [Edge<
    at createNewSchemaObjectFromGeneric (/myproject/node_modules/graphql-s2s/src/graphqls2s.js:439:26)
    at _.filter.map.join._.map.value (/myproject/node_modules/graphql-s2s/src/graphqls2s.js:477:16)
    at /myproject/node_modules/lodash/lodash.js:3555:27
    at /myproject/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/myproject/node_modules/lodash/lodash.js:3002:24)
    at /myproject/node_modules/lodash/lodash.js:4886:18
    at baseMap (/myproject/node_modules/lodash/lodash.js:3554:7)
    at Function.map (/myproject/node_modules/lodash/lodash.js:9546:14)
    at interceptor (/myproject/node_modules/lodash/lodash.js:16983:35)
    at Function.thru (/myproject/node_modules/lodash/lodash.js:8787:14)
```

Any idea? 😄

**Comment by nicolasdao** [comment]
Hi @lobodart ,

I'm a bit busy now, but I should be able to come back to you within 48 hours.

**Comment by nicolasdao** [comment]
Hi @lobodart,

That should be fixed in the latest version (@0.12.1). Could you please let me know if that resolves your issue?

**Comment by chasingmaxwell** [comment]
I'm still having this problem on `0.15.0`.

**Comment by chasingmaxwell** [comment]
Hi @nicolasdao! Thanks for the quick response. Here's a simple example that throws the same error as the OP.

```JavaScript
const { transpileSchema } = require('graphql-s2s').graphqls2s;

const schema = `
type Shelf<T> {
  tiles: [T]
}

type Tile {
  title: String
}

type Page {
  shelves: [Shelf<Tile>]
}`;

module.exports = {
  typeDefs: [transpileSchema(schema)],
};
```

Here's the error I receive:

```
[...]/node_modules/graphql-s2s/src/graphqls2s.js:548
		if (!baseGenObj) throw new Error(`Schema error: Cannot find any definition for generic type starting with ${genObjName}`)
		                 ^

Error: Schema error: Cannot find any definition for generic type starting with [Shelf<
    at createNewSchemaObjectFromGeneric ([...]/node_modules/graphql-s2s/src/graphqls2s.js:548:26)
    at _.filter.forEach.value ([...]/node_modules/graphql-s2s/src/graphqls2s.js:621:21)
    at arrayEach ([...]/node_modules/lodash/lodash.js:508:11)
    at Function.forEach ([...]/node_modules/lodash/lodash.js:9334:14)
    at LodashWrapper.object.(anonymous function) [as forEach] ([...]/node_modules/lodash/lodash.js:15706:25)
    at buildSchemaString ([...]/node_modules/graphql-s2s/src/graphqls2s.js:621:4)
    at chain.next.next.data ([...]/node_modules/graphql-s2s/src/graphqls2s.js:664:17)
    at Object.next ([...]/node_modules/graphql-s2s/src/utilities.js:21:45)
    at transpileSchema ([...]/node_modules/graphql-s2s/src/graphqls2s.js:664:4)
    at Object.<anonymous> ([...]/example.js:17:14)
```
